### ISSUE TITLE
-MFB Bug Report-

### ISSUE THREAD

**Issue by 69Catman** [happybandit360/MFB#11]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose? (**Survival**/Creative, Single Player/LAN/**Server**)
* What mods had you unlocked in your game?
Bewitchment, Viescraft, RFTools, Calculator
* Is there any other game information that might be related?

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? (If not, please attempt to reproduce before submitting an issue report)
Witches Oven produces charcoal when lit with nothing to smelt.

## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior?
Bonus Charcoal is produced

## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug?

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1.Place fuel into oven
2.Smelt one item
3.Remove Product
4.Observe
*(Add more as needed)*

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version:0.0.4a
* Java Version:build 1.8.0_201-b09
* Launcher Used:Native
* Memory Allocated:7936 Mb
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

**Comment by happybandit360** [comment]
Removed Bewitchment for the foreseeable future.
