### ISSUE TITLE
Thaumic JEI

### ISSUE THREAD

**Issue by BoneDisturbed1** [happybandit360/MFB#13]
If making a suggestion for changes to this modpack, please provide as much information as possible and please fill out all sections.

## **Suggestion Type** (**NEW**, CHANGE, OTHER)
Thaumic JEI

## **Suggestion Description** (Please be as descriptive as possible)
Just overall Quality of Life mod if Thaumcraft is unlocked

## **Reason for Suggestion** (Please be as descriptive as possible)
Quality of Life
## Mod Details (For new or replacement mods)
* Name: Thaumic JEI
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/thaumic-jei

**Comment by happybandit360** [comment]
Will keep in mind if Thaumcraft compatibility fix works out.

**Comment by happybandit360** [comment]
Had to remove Thaumcraft
