### ISSUE TITLE
-MFB Bug Report- Invisible items in JEI

### ISSUE THREAD

**Issue by BoneDisturbed1** [happybandit360/MFB#22]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose? (### **_Survival/Creative, Single Player/LAN/Server_**)
* What mods had you unlocked in your game?
Tetra & Astral Sorcery 
* Is there any other game information that might be related?

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? (If not, please attempt to reproduce before submitting an issue report)
JEI shows a gab between items with invisible items some with names.

## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior?
Hidden in JEI

## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug?
Hide in JEI

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. Open JEI 
2. Search @tetra or @astral
*(Add more as needed)*

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: 0.2.1
* Java Version: ?!?
* Launcher Used: Twitch
* Memory Allocated: 10 Gigs
* Server/LAN/Single Player: Server, LAN and Single Player
* Optifine Installed: Nope
* Shaders Enabled: Noperino

**Comment by BoneDisturbed1** [comment]
Add Carry On to the list

**Comment by happybandit360** [comment]
Got it. Will do another through JEI sweep as part of the full release checklist, but invisible things like that would be easy to miss.
