### ISSUE TITLE
Akashic Tome lost when accessing book from unlearned mod

### ISSUE THREAD

**Issue by natelovesyou** [happybandit360/MFB#23]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose?
Survival.
* What mods had you unlocked in your game?
Actually Additions, Redstone Arsenal, Compact Machines, and Wizardry.
* Is there any other game information that might be related?
Nothing comes to mind.

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug?
The Akashic Tome is removed, and replaced by the book you clicked (which is promptly dropped). The Tome cannot be recovered. I have reproduced it a few times in the beta server.

## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior?
Asking what happens instead of the expected behavior makes no sense for this section (from a person who does software Quality Assurance professionally). You already asked what the current behavior is in the previous section. Instead, I will go by the title: Expected behavior.

Expected behavior: The Tome can open the target book without being lost/replaced.

## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug?
Make it so that ALL books contained within the Tome are familiar items and can therefore be read...that's my best suggestion.
The mod that handles stages/unfamiliar items doesn't play well with the Akashic Tome. Perhaps the mod creators need to be notified, if a tweak on the pack's end doesn't help of course.

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. Open the Akashic Tome.
2. Find a book from a mod that you have not yet learned. For me, it was the Lexica Botania (the advanced knowledge version, not the basic one).
3. Click that book.

This is 100% reproducible for me.

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.
No crash log. The log is huge, and exceeds all site's limits. Sorry.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: MFB-Beta-0.2.2b
* Java Version: 8.0.2210.11
* Launcher Used: Twitch
* Memory Allocated: 6 GBs
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by happybandit360** [comment]
Fixed in a624931ce8acf84e9be8b707828d4a85f4d80a2f
