### ISSUE TITLE
-MFB Bug Report- autocrafter

### ISSUE THREAD

**Issue by HSavageheart** [happybandit360/MFB#28]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose? (Survival/Server)
* What mods had you unlocked in your game?
enderio/Actualadditions/tinkers/rftools/Astral/industrialforegoing/mekanism/thermal/mystAgr/mobgrinding
* Is there any other game information that might be related?

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? (If not, please attempt to reproduce before submitting an issue report)
auto crafting lava buckets with rftools, ender io and mystagr (essence)
is not working.
## **Expected Behavior**
should be crafting lava buckets
If describing a bug, what happens instead of the expected behavior?

## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug?
no clue first time that it happens in a pack for me.
## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. https://streamable.com/fz72y
2. https://streamable.com/83qx5
*(Add more as needed)*

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.
no log

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: 0.3.2b
* Java Version: jre 1.8.0-181
* Launcher Used:MultiMC
* Memory Allocated:8000MB
* Server/LAN/Single Player: Happy's test server
* Optifine Installed: nope
* Shaders Enabled: nope

**Comment by HSavageheart** [comment]
Actually I think that its any recipe with essence in it

**Comment by HSavageheart** [comment]
autocrafters don't work in general. tried to auto craft stone slabs

**Comment by happybandit360** [comment]
Appears to only be bucket-based recipes that have problems with autocrafters. This has been noticed in other packs as well.
