### ISSUE TITLE
silent's gear (mentioned in dev stream)

### ISSUE THREAD

**Issue by MitztheKat** [happybandit360/MFB#31]
If making a suggestion for changes to this modpack, please provide as much information as possible and please fill out all sections.

## **Suggestion Type** (NEW, CHANGE, OTHER)
**CHANGE** - Tetra to Silent Gear

## **Suggestion Description** (Please be as descriptive as possible)
Replacing Tetra with Silent gear, two similar tool mods, but one less invasive & total JEI support, and one with a fancy GUI with confusion in every single place.
## **Reason for Suggestion** (Please be as descriptive as possible)
Tetra has caused several incidents in my private enigmatica 4 worlds, and I have found that Silent Gear has a much more stable/flexible system - no bugs, easily modifiable tools, mattocks (yes!!) It's my preference for a Tinker's Construct replacement... at least, the 1.14 version... dinnae if the one commonly used in 1.14 is available somewhat in 1.12.
## Mod Details (For new or replacement mods)
* Name: Silent's Gear
* CurseForge Link: [https://www.curseforge.com/minecraft/mc-mods/silent-gear](url)
Just following up from the dev stream today!

**Comment by happybandit360** [comment]
Added
