### ISSUE TITLE
add Wireless Crafting Terminal for wireless ME system

### ISSUE THREAD

**Issue by LooseCannon711** [happybandit360/MFB#32]
If making a suggestion for changes to this modpack, please provide as much information as possible and please fill out all sections.

## **Suggestion Type** (NEW, CHANGE, OTHER)
NEW

## **Suggestion Description** (Please be as descriptive as possible)
The Wireless Crafting Terminal adds a wireless crafting terminal and infinity booster card for ae2. the infinity booster allows people to access there ME system from anywhere in the world/dimensions.

## **Reason for Suggestion** (Please be as descriptive as possible)
The Wireless Crafting Terminal adds a wireless crafting terminal and infinity booster card for ae2. the infinity booster allows people to access there ME system from anywhere in the world/dimensions.

## Mod Details (For new or replacement mods)
* Name: Wireless Crafting Terminal
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal

**Comment by happybandit360** [comment]
Added
