### ISSUE TITLE
-MFB Bug Report- Osmium ingot recipe from mystical ag

### ISSUE THREAD

**Issue by FearowGaming** [happybandit360/MFB#33]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose?(Survival/Creative, Single Player/LAN/Server)
Server
* What mods had you unlocked in your game? Mystical Ag
* Is there any other game information that might be related?

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? (If not, please attempt to reproduce before submitting an issue report)  
Osmium ingots can't be crafted from the mystical ag osmium essence

## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior?
recipe showing in JEI

## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug? 
Make a crafting recipe for osmium ingots from mystical ag osmium essence

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1.Open JEI
2.Search osmium ingot
3. click on the item
4.  Confusion as to why the recipe isn't showing
    (Add more as needed)

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.
Not created

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: Beta 0.3.2b
* Java Version: Java 8 231
* Launcher Used: MultiMc
* Memory Allocated: 4G
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by happybandit360** [comment]
Recipe fixed in dev
