### ISSUE TITLE
-AE2 modded crafting Bug Report-

### ISSUE THREAD

**Issue by LooseCannon711** [happybandit360/MFB#34]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose? (Survival/Creative, Single Player/LAN/Server) Survival/Creative, Single Player/LAN/Server
* What mods had you unlocked in your game? AE2
* Is there any other game information that might be related? 

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? (If not, please attempt to reproduce before submitting an issue report)
AE2 does not crafting modded item, as it might be a fake player
## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior?
crafting modded items
## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug?
add the [AE2] or [Minecraft] in the fakeplayer config
## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1.
2.
*(Add more as needed)*

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by happybandit360** [comment]
Fixed in dev
