### ISSUE TITLE
Missing Recipe from XL Food Mod

### ISSUE THREAD

**Issue by BrotherBaoGe** [happybandit360/MFB#36]
Found a missing recipe from XL Food Mod for Cappucino, you can't craft a mug of coffee with a bucket of milk to make it normally as per curse, https://www.curseforge.com/minecraft/mc-mods/xl-food-mod, but if you do on the current MFB-Beta-0.4.2b, you get coffee which does not register itself as a Cappucino if you consume it and there are no other methods to reproduce or to craft a Cappucino.

**Comment by happybandit360** [comment]
Recipes fixed and added
