### ISSUE TITLE
-MFB Bug Report- ElectroBlob's Wizardry Wand recharging

### ISSUE THREAD

**Issue by monkeybug34** [happybandit360/MFB#37]
## **Game Information**
Tested in Singleplayer and on the test server, both in Survival mode.

Only unlocked Electroblob's wizardry in Singleplayer. Tinker's, Thermal Ex, EB's Wizardy, Evilcraft and Random things on test server

as this appears to be a crafting bug, Ihave tested it in a vanilla 3x3 table and the inventory 2x2 table to ensure this is not a inter-mod incompatibility.

## **Bug Report**
When attempting to craft a wand from EB's Wizardry and a mana vial of any size, the result of the craft (The wand, but with additional mana) actually returns the wand, but all the mana will be drained. I have tested this in the Simple storage networks' crafting interface, as well as the vanilla crafting table and the inventory 2x2 grid. all produce a wand that has been discharged of all mana.

## **Expected Behavior**
The expected result of this crafting recipe should be the same wand that you put into the grid, with all it's data intact and the value of mana increased dependent on what size of mana vial was used.

## **Possible Solution**
possible solution: update/backdate the mod.
possible solution: see if CraftTweaker2 is causing issues by removing it for one test case.
reason: unknown. possibly something to do with the recipe handler. 

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. craft a new wand of any element (only tested with fire element) the wand crafted should contain no mana.
2. attempt to craft the wand with a mana vial of any size.

## **Logs**
No crash logs.

## **Client Information**
* Modpack Version: 0.4.2b
* Java Version: Bundled Java version
* Launcher Used: Twitch
* Memory Allocated: 6144 MB
* Server/LAN/Single Player: Server and Singleplayer. Suspected LAN as well.
* Optifine Installed: no additional modifications installed.
* Shaders Enabled: no additional modifications installed.

**Comment by happybandit360** [comment]
Appears to be an incompatibility between Electroblobs and RecipeStages. Removed script to stage recipes and it is working properly.

**Comment by monkeybug34** [comment]
Thanks. if we were to patch this quickly on the test server, would we need to fix the script serverside?

**Comment by happybandit360** [comment]
I'd have to check with James on that

**Comment by happybandit360** [comment]
Looks like it would have to be changed on both sides (client and server), so unfortunately, we won't be able to do anything for this iteration.
