### ISSUE TITLE
-MFB Bug Report- Carry On mod and Flat Transfer Nodes 

### ISSUE THREAD

**Issue by Dogvomit** [happybandit360/MFB#38]
## **Game Information**
* What mode were you playing in when the issue arose?
      MFB Server
* What mods had you unlocked in your game?
     Tinkers, Ender IO, Random Things.

## **Bug Report**
Picking up a chest with a Flat Transfer Node attached to it deletes the Flat Transfer Node.

## **Expected Behavior**
I would expect the Flat Transfer Node to pop off like if you had broken the chest.

## **Possible Solution**
Not sure if it's fixable, The carry on mod would need to detect it?

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. Place Flat Transfer Node onto the side of a chest
2. Pick up the chest.

## **Logs**
No error triggered.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: MFB-Beta-0.4.2b
* Java Version: 1.8.0_51 64bit
* Launcher Used: Twitch
* Memory Allocated:
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by happybandit360** [comment]
Unfortunately this is a issue with Carry On and Extra Utilities that I will not be able to fix for the pack. I have made some other changes that likely will cause the transfer nodes to be used less anyway.
