### ISSUE TITLE
-MFB Bug Report- Chiseled Limestone

### ISSUE THREAD

**Issue by Dogvomit** [happybandit360/MFB#39]
## **Game Information**
* What mode were you playing in when the issue arose?
      MFB Server
* What mods had you unlocked in your game?
     Tinkers, Ender IO, Random Things.

## **Bug Report**
Chiseling Limestone from within the GUI, three of the block don't give the correct results.
  Block #6854/5 changes to #6662/0
  Block #6662/0 changes to #6662/1
  Block #6662/1 changes to #6854/5

Chiseling outside of the GUI is fine, I can chisel the Limestone block to one of the three blocks and brake it getting the correct block to drop.

Tested with all three Chisels. (Chisel, Dimond Chisel and iChisel)
 
## **Expected Behavior**
I would expect to get the block I clicked on when chiseling from the GUI.

## **Possible Solution**
Tweek the crafting recipe?

## **Steps to Reproduce**

Link to example --> https://www.dropbox.com/s/byozb4xg7wo1oey/MFB%20Bug%20%2339%20-%202020-02-12%2016-19-25-957.mp4?dl=0

## **Logs**
No error triggered.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: MFB-Beta-0.4.2b
* Java Version: 1.8.0_51 64bit
* Launcher Used: Twitch
* Memory Allocated:
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by happybandit360** [comment]
Have been unable to reproduce this issue. I think it may be a fluke? Let me know if the issue continues and I'll dig into it again.
