### ISSUE TITLE
Crash Log:Enchanting Plus

### ISSUE THREAD

**Issue by BrotherBaoGe** [happybandit360/MFB#40]
Tried to put a diamond sword, not from boss drops, into the Enchanting Plus Advanced Enchantment Table but items such as boss drops work just not:
[Epic] Diamond Sword I have called the "Quartz-Fused Swift Striking Diamond Sword of Domination"
_When in hand:_
+93.39% Attack Speed
_1.6 Attack Speed
7 Attack Damage_
+96.65% Critical Damage

I don't recall where exactly this weapon was obtained.

https://paste.dimdev.org/ixucuqates.mccrash

**Comment by happybandit360** [comment]
Was the crash on the Boss Drop weapon or a normal weapon?
