### ISSUE TITLE
Construct's Armory Metal Options

### ISSUE THREAD

**Issue by Dogvomit** [happybandit360/MFB#42]
## **Suggestion Type** (NEW, CHANGE, OTHER)
*CHANGE/OTHER* 

## **Suggestion Description** (Please be as descriptive as possible)
Add/enable more metal options in Construct's Armory.
   Mystical Agriculture - Molten Superium and Supremium.
   Industrial Foregoing - Pink Slime and Reinforced Pink Slime.
   PlusTiC - Molten metals like Osgloglas
   
## **Reason for Suggestion** (Please be as descriptive as possible)
To give the same metal options as Tinkers Construct and PlusTiC

**Comment by happybandit360** [comment]
As far as I can tell, Construct Armory does not have support for those. Have you seen them in other packs?

**Comment by Dogvomit** [comment]
Doing some testing.
It looks like Armory Expansion mod adds some integration with other mods.
I added it to a test project and was able to get Supremium and Osgloglas to show up.
![Armor](https://user-images.githubusercontent.com/3184127/74895068-52394800-5356-11ea-999a-4d3280647d93.jpg)




Haven't figured out what adds Pink Slime and Reinforced Pink Slime integration to Construct's Armory.   
I am able to make the Pink Slime Ingots and smelt them but unable to cast them into CA parts.

**Comment by happybandit360** [comment]
Ok. Looked at it, looks cool. Testing it out, but probably will add it in. Thanks for the suggestion.
