### ISSUE TITLE
-MFB Bug Report-

### ISSUE THREAD

**Issue by Kelitore** [happybandit360/MFB#46]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose? (Survival/Creative, Single Player/LAN/Server )
Survival/Single player
* What mods had you unlocked in your game?
Blood Magic, Modular powersuits, Matter overdrive, Compact Machines.
* Is there any other game information that might be related?
Carry on Mod.

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? (If not, please attempt to reproduce before submitting an issue report)
Using Carry on to pick up the Arcane ashes ritual in Blood Magic with items that do not start a ritual and attempting to place it back down results in duplicating the entire thing items and all. Can reproduce.
## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior?
Should just be picked up and  placed, but instead stays in your hands and you can keep placing it, all you do to reproduce is hold your carry on button, pick it up, keep holding the button and right click to place on ground, it doesn't happen every single time, but it will often. It will keep placing it as many times as you did while holding the carry on button after you let go of it and try to place it again. Breaking Arcane ashes results in getting the items in it for every time you placed it.
## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug?
Black list Arcane ashes, also should already be done in an update when made as I reported it to mod owners github as well.
## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. Place Arcane Ashes on ground put items in that don't start ritual.
2. Pick up with Carry on, do not release carry on button.
3. While holding button right click to place. (item will stay in hand)
4. After letting go of carry on button right click to place, it will place as many times as did when  you held button.
5. Break all Arcane ashes, not all will have icon but will have bounding box, and items will continue to pop out until original is broken.
6. This doesn't happen 100% of the time.
*(Add more as needed)*

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: 1.0.1
* Java Version: 8.0.2410.7
* Launcher Used: Twicht
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by happybandit360** [comment]
Added to Carry On blacklist
