### ISSUE TITLE
Flint Dropping Not Working

### ISSUE THREAD

**Issue by Mar3xgg** [happybandit360/MFB#5]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose? (Survival/Creative, Single Player/LAN)
Survival Server
* What mods had you unlocked in your game?
Flexible Tools, Project Red, Roots, and Ender Utilities

* Is there any other game information that might be related?
Not that I know of

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? (If not, please attempt to reproduce before submitting an issue report)

Flint is uncraftable and cannot be gotten from breaking gravel in any form/with any tools, even when breaking gravel with fortune 3 which should have 100% drop chance

## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior?

Nothing drops except for gravel
## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug?

pickle tweaks config

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. place gravel/find it
2. break gravel/try to craft 3 gravel to flint
3. it doesn't give you flint under any circumstances, even crafting
*(Add more as needed)*

## **Logs**
Please provide links (PasteBin/Gist/Pastee/Etc) to crash logs relevant to this issue, if possible.

N/A
## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: 0.0.3
* Java Version: 1.8_211
* Launcher Used: MultiMC
* Memory Allocated: 7168MB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by PseudoFyre** [comment]
This is probably the config that needed changing

```
# Should Flint dropped from Gravel be replaced with the item defined in 'flint_drop_item'? [default: true]
B:flint_drop=true

# Define the item that should replace Flint from Gravel. 
# - Syntax: modid:itemid:meta
S:flint_drop_item=minecraft:gravel:0
```

**Comment by PseudoFyre** [comment]
I changed it and sent a pull request

**Comment by happybandit360** [comment]
Will be fixed in next update. Also will be adding gravel to flint recipe.
